# Déclaration d’un VirtualHost écoutant sur le port 80
<VirtualHost *:80>

    # Email de l’administrateur du site
    ServerAdmin thierno.mouhamadou.d.diallo@etu.univ-st-etienne.fr

    # Nom du serveur (localhost dans un conteneur)
    ServerName localhost

    # Répertoire racine du site Symfony (le dossier public)
    DocumentRoot /var/www/html/site/public

    # Configuration des permissions sur le dossier public
    <Directory /var/www/html/site/public>

        # Désactive les .htaccess (on utilise la conf Apache)
        AllowOverride None
	
	# Autorise l'accès au dossier (Apache 2.4)
	Require all granted

        # Active le moteur de réécriture si le module est chargé
        <IfModule mod_rewrite.c>
            RewriteEngine On

            # Si l’URL contient une extension (ex: .css, .js, .png)
            RewriteCond %{REQUEST_URI} \..+$

            # … mais que ce n’est pas un fichier .html
            RewriteCond %{REQUEST_URI} !\.html$

            # Alors on ne réécrit pas
            RewriteRule .* - [L]

            # Sinon, on redirige tout vers index.php (Symfony)
            RewriteRule ^(.*)$ index.php [QSA,L]
        </IfModule>

    </Directory>

</VirtualHost>

